# Generated by Django 5.2.15 on 2026-07-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_comment_group_post_group_message_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Лайк'), ('comment', 'Коментар'), ('repost', 'Репост'), ('subscribe', 'Нова підписка'), ('message', 'Нове повідомлення'), ('group_invite', 'Запрошення до групи')], max_length=20, verbose_name='Тип сповіщення'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
