# Generated by Django 5.2.15 on 2026-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_content_type_remove_post_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('accepted', 'Підтверджено')], default='accepted', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Дописи, друзі та підписки видно лише підписникам', verbose_name='Приватний акаунт'),
        ),
    ]
