# Generated by Django 5.2.10 on 2026-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat_creator_message_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('accepted', 'Прийнято'), ('pending', 'Очікує підтвердження')], default='accepted', help_text='Для приватного чату зі стороннім користувачем (не другом) — "Очікує підтвердження", доки одержувач не прийме запит на повідомлення.', max_length=10, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
