# Generated by Django 5.2.10 on 2026-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chat_status_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Лише для групових чатів. Змінювати може власник (creator).', null=True, upload_to='chats/avatars/', verbose_name='Аватар чату'),
        ),
    ]
